version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports: [1025, 1080]
###< symfony/mailer ###

###> symfony/mercure-bundle ###
  mercure:
    ports:
      - 9090:80
###< symfony/mercure-bundle ###
